name: Deploy application to VPS
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 720
          script: |
            cd /home/mb/donneur-production/Donneur

            # Fetch the latest code
            git pull origin main

            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh

            # Frontend Build
            cd donneur-webapp
            npm install
            npm run build

            # Move the build to the correct location
            sudo rm -rf /var/www/donneur-production/*
            sudo cp -r dist/* /var/www/donneur-production/

            # Restart Gunicorn
            sudo systemctl restart donneur-api.service

            # Restart Nginx
            sudo systemctl restart nginx