name: Deploy TEST to VPS
on:
  push:
    branches:
      - maxim

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/donneur_test/Donneur

            # Fetch the latest code
            git pull

            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh

            # Frontend Build
            cd donneur-webapp
            npm install
            npm run build

            # Move the build to the correct location
            rm -rf /var/www/donneur-test/*
            cp -r dist/* /var/www/donneur-test/

            # Restart Gunicorn
            sudo systemctl restart donneur-api-test.service

            # Restart Nginx (if needed)
            sudo systemctl restart nginx